default_environment: default
environments:
    DEVELOPMENT:
        connections:
            duckdb:
                - name: duckdb-default
                  path: /Users/robin/Desktop/bruin_test/bruin/dev_duckdb.db
            postgres:
                - name: postgres1
                  username: postgres
                  password: admin
                  host: localhost
                  port: 5433
                  database: postgres
                  schema: public
                  pool_max_conns: 10
                  ssl_mode: allow
            chess:
                - name: chess-default
                  players:
                    - MagnusCarlsen
                    - Hikaru
    PROD:
        connections:
            duckdb:
                - name: prod_duckdb
                  path: /Users/robin/Desktop/bruin_test/bruin/prod_duckdb.db
            postgres:
                - name: postgres1
                  username: postgres
                  password: admin
                  host: localhost
                  port: 5433
                  database: postgres
                  schema: public
                  pool_max_conns: 10
                  ssl_mode: allow
    PreProd:
        connections:
            duckdb:
                - name: preprod_duckdb
                  path: /Users/robin/Desktop/bruin_test/bruin/preprod_duckdb.db
            postgres:
                - name: postgres1
                  username: postgres
                  password: admin
                  host: localhost
                  port: 5433
                  database: postgres
                  schema: public
                  pool_max_conns: 10
                  ssl_mode: allow
    default:
        connections:
            postgres:
                - name: postgres1
                  username: postgres
                  password: admin
                  host: localhost
                  port: 5433
                  database: postgres
                  schema: public
                  pool_max_conns: 10
                  ssl_mode: allow
            duckdb:
                - name: duckdb-default
                  path: /Users/robin/Desktop/bruin_test/bruin/duckdb.db
            chess:
                - name: chess-default
                  players:
                    - MagnusCarlsen
                    - Hikaru
        